version: "3.3"

services:
  backend:
    container_name: "app_backend"
    build: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app/backend
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=TASK_LIST
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-i", ":3001"]
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    container_name: "app_frontend"
    build: ./front-end
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy

  db:
    container_name: "mysql_db"
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
